apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: chase
  name: paddlejob
rules:
- apiGroups:
  - batch.paddlepaddle.org
  resources:
  - paddlejobs
  verbs:
  - get
  - list
  - create
  - delete
  - update
  - patch
  - watch