apiVersion: batch.paddlepaddle.org/v1
kind: PaddleJob
metadata:
  name: paddle-simple-cpu
spec:
  withGloo: 1
  worker:
    replicas: 2
    template:
      spec:
        containers:
          - name: paddle
            image: chasechristensen/paddle_cpu:1.0
            command:
              - python
            args:
              - "-m"
              - paddle.distributed.launch
              - "run_check"
              - "paddle_train_dist.py"
            ports:
              - containerPort: 37777
                name: master
            imagePullPolicy: Always
  ps:
    replicas: 2
    template:
      spec:
        containers:
          - name: paddle
            imagePullPolicy: Always