apiVersion: "kubeflow.org/v1"
kind: "TFJob"
metadata:
  name: "dist-mnist-for-e2e-test-2"
spec:
  tfReplicaSpecs:
    PS:
      replicas: 2
      restartPolicy: Never
      template:
        
        metadata:
          annotations:
              sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: tensorflow
              image: chasechristensen/tf-mnist-dist:2.0
    Worker:
      replicas: 3
      restartPolicy: Never
      template:
        metadata:
          annotations:
              sidecar.istio.io/inject: "false"
        spec:      
          containers:
            - name: tensorflow
              image: chasechristensen/tf-mnist-dist:2.0

