apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-dist-mnist-gloo2"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: chasechristensen/pytorch-mnist-kf:v1
              args: ["--backend", "gloo"]
              # Comment out the below resources to use the CPU.
              #resources: 
               # limits:
                #  nvidia.com/gpu: 1
    Worker:
      replicas: 3
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers: 
            - name: pytorch
              image: chasechristensen/pytorch-mnist-kf:v1
              args: ["--backend", "gloo"]
              # Comment out the below resources to use the CPU.
              #resources: 
               # limits:
                #  nvidia.com/gpu: 1
