apiVersion: "kubeflow.org/v1"
kind: "MXJob"
metadata:
  name: "auto-tuning-job"
spec:
  jobMode: MXTune
  mxReplicaSpecs:
    TunerTracker:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations: 
            sidecar.istio.io/inject: "false"
        spec:    
          containers:
          - name: mxnet
            image: chasechristensen/mxtune:1.0
            imagePullPolicy: Always
            command: ["python3"]
            args: ["/home/scripts/start-job.py"]
    TunerServer:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations: 
            sidecar.istio.io/inject: "false"       
        spec:     
          containers:
          - name: mxnet
            image: chasechristensen/mxtune:1.0
            imagePullPolicy: Always
            command: ["python3"]
            args: ["/home/scripts/start-job.py"]
    Tuner:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          annotations: 
            sidecar.istio.io/inject: "false" 
        spec:
          containers:
          - name: mxnet
            image: chasechristensen/mxtune:1.0
            command: ["python3"]
            args: ["/home/scripts/start-job.py"]
            imagePullPolicy: Always

